from enum import Enum

class RestrictionEnum(Enum):
    NO_MAX_ASSIGNMENTS_PER_TEACHER='NO_MAX_ASSIGNMENTS_PER_TEACHER'
    NO_PERIODS_FOR_LUNCH='NO_PERIODS_FOR_LUNCH'
    SCHEDULE_START_TIME='SCHEDULE_START_TIME'
    SCHEDULE_END_TIME='SCHEDULE_END_TIME'
    PERIODS_DURATION='PERIODS_DURATION'
    MAX_NUMBER_OF_STUDENTS_PER_CLASS='MAX_NUMBER_OF_STUDENTS_PER_CLASS'
    MIN_NUMBER_OF_STUDENTS_PER_CLASS='MIN_NUMBER_OF_STUDENTS_PER_CLASS'

class PriorityTypeEnum(Enum):
    COURSE=1
    COURSE_AREA=2
    COURSE_SEMESTER=3
    COURSE_NO_STUDENTS=4
    COURSE_SCHEDULE=11
    CLASS= 5
    CLASS_SPACE_CAPACITY=6
    CLASS_SCHEDULE_AREA=7
    TEACHER=8
    TEACHER_SCHEDULE=9
    TEACHER_COURSE_PRIORITY=10
    COURSE_MANDATORY=15

class StatusEnum(Enum):
    IN_PROGRESS=13
    FINISHED=14
    ACTIVE=16
    INACTIVE=17