"""empty message

Revision ID: 0795c9802960
Revises: 6c3ba57ccb38
Create Date: 2023-08-28 23:11:16.836029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0795c9802960'
down_revision = '6c3ba57ccb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restriction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_area_configuration',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['status'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_class_configuration',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('class_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['status'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_capacity', sa.Integer(), nullable=False))
        batch_op.drop_column('number')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('no_periods', sa.Integer(), nullable=False))

    with op.batch_alter_table('course_op', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_periods', sa.Integer(), nullable=False))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.BIGINT(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'type', ['version'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['status'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('version')
        batch_op.drop_column('status')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('course_op', schema=None) as batch_op:
        batch_op.drop_column('no_periods')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('no_periods')
        batch_op.drop_column('credits')
        batch_op.drop_column('code')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('space_capacity')

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    op.drop_table('schedule_class_configuration')
    op.drop_table('schedule_area_configuration')
    op.drop_table('restriction')
    # ### end Alembic commands ###
