"""empty message

Revision ID: 0b92f954f0e2
Revises: 0b9faa63c1ae
Create Date: 2023-09-18 12:40:20.272413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b92f954f0e2'
down_revision = '0b9faa63c1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
