"""empty message

Revision ID: 0b9faa63c1ae
Revises: 020931a76b37
Create Date: 2023-09-18 02:07:02.169901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9faa63c1ae'
down_revision = '020931a76b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_teacher_oc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'area_oc', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_teacher_oc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
