"""empty message

Revision ID: 143fbc93c537
Revises: 63599c6b9f86
Create Date: 2023-09-08 02:50:03.784300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143fbc93c537'
down_revision = '63599c6b9f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=150), nullable=True))

    with op.batch_alter_table('area_oc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area_oc', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
