"""empty message

Revision ID: 17419750d15c
Revises: 930759c4d73d
Create Date: 2023-08-20 18:13:39.651317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17419750d15c'
down_revision = '930759c4d73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic_class',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('class_id', sa.BIGINT(), nullable=False),
    sa.Column('characteristic_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_characteristic',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restriction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.BIGINT(), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('parent_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('type')
    op.drop_table('teacher_schedule')
    op.drop_table('restriction')
    op.drop_table('course_schedule')
    op.drop_table('course')
    op.drop_table('class_characteristic')
    op.drop_table('class')
    op.drop_table('characteristic_class')
    op.drop_table('assignment')
    # ### end Alembic commands ###
