"""empty message

Revision ID: 1b057929c2ca
Revises: 
Create Date: 2023-09-07 00:49:50.295814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b057929c2ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('space_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('space_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_criteria',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('parent_type', sa.BIGINT(), nullable=True),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('class_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_schedule_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('class_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area_oc.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_oc.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('no_periods', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restriction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('parent_id', sa.BIGINT(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.BIGINT(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('no_periods', sa.Integer(), nullable=True),
    sa.Column('no_students', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_teacher',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_area_configuration',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.BIGINT(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['status'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_class_configuration',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('class_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_oc.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['status'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_configuration_priority_criteria',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('priority_criteria_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['priority_criteria_id'], ['priority_criteria.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_restriction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('class_id', sa.BIGINT(), nullable=True),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('no_students', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class_oc.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course_oc.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_oc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_schedule_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_oc.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_teacher_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_oc.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_oc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_schedule_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area_oc.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_oc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_schedule_oc')
    op.drop_table('course_teacher_oc')
    op.drop_table('course_schedule_oc')
    op.drop_table('assignment')
    op.drop_table('teacher_oc')
    op.drop_table('schedule_restriction')
    op.drop_table('schedule_configuration_priority_criteria')
    op.drop_table('schedule_class_configuration')
    op.drop_table('schedule_area_configuration')
    op.drop_table('course_teacher')
    op.drop_table('course_schedule')
    op.drop_table('course_oc')
    op.drop_table('teacher_schedule')
    op.drop_table('schedule')
    op.drop_table('restriction')
    op.drop_table('course')
    op.drop_table('class_schedule_oc')
    op.drop_table('class_schedule')
    op.drop_table('type')
    op.drop_table('teacher')
    op.drop_table('priority_criteria')
    op.drop_table('class_oc')
    op.drop_table('class')
    op.drop_table('area_oc')
    op.drop_table('area')
    # ### end Alembic commands ###
