"""empty message

Revision ID: 3f5e28295ed3
Revises: 932e651016e0
Create Date: 2023-09-15 00:57:22.596698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5e28295ed3'
down_revision = '932e651016e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule_oc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'area_oc', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule_oc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
