"""empty message

Revision ID: 4fd713f4d0cb
Revises: 0b92f954f0e2
Create Date: 2023-09-18 16:42:16.701327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd713f4d0cb'
down_revision = '0b92f954f0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efficiency', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('efficiency')

    # ### end Alembic commands ###
