"""empty message

Revision ID: 63599c6b9f86
Revises: 1b057929c2ca
Create Date: 2023-09-07 23:39:57.260435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63599c6b9f86'
down_revision = '1b057929c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_assignment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('no_students', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schedule_class_configuration')
    with op.batch_alter_table('class_oc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('schedule_id', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'type', ['status'], ['id'])
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['id'])

    with op.batch_alter_table('priority_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('subtype', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'type', ['type'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['subtype'], ['id'])

    with op.batch_alter_table('schedule_area_configuration', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_area_configuration_area_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'area_oc', ['area_id'], ['id'])

    with op.batch_alter_table('schedule_configuration_priority_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('subtype', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('asc', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.drop_constraint('schedule_configuration_priority_crite_priority_criteria_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'type', ['subtype'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['type'], ['id'])
        batch_op.drop_column('priority_criteria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_configuration_priority_criteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_criteria_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_configuration_priority_crite_priority_criteria_id_fkey', 'priority_criteria', ['priority_criteria_id'], ['id'])
        batch_op.drop_column('order')
        batch_op.drop_column('asc')
        batch_op.drop_column('description')
        batch_op.drop_column('subtype')
        batch_op.drop_column('type')

    with op.batch_alter_table('schedule_area_configuration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_area_configuration_area_id_fkey', 'area', ['area_id'], ['id'])

    with op.batch_alter_table('priority_criteria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subtype')
        batch_op.drop_column('type')

    with op.batch_alter_table('class_oc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_id')
        batch_op.drop_column('status')

    op.create_table('schedule_class_configuration',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('area_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], name='schedule_class_configuration_area_id_fkey'),
    sa.ForeignKeyConstraint(['class_id'], ['class_oc.id'], name='schedule_class_configuration_class_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='schedule_class_configuration_schedule_id_fkey'),
    sa.ForeignKeyConstraint(['status'], ['type.id'], name='schedule_class_configuration_status_fkey'),
    sa.PrimaryKeyConstraint('id', name='schedule_class_configuration_pkey')
    )
    op.drop_table('course_assignment')
    # ### end Alembic commands ###
