"""empty message

Revision ID: 6c3ba57ccb38
Revises: 1085444b0746
Create Date: 2023-08-24 23:36:25.145925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3ba57ccb38'
down_revision = '1085444b0746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_characteristic_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priority_criteria',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic_class_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('class_id', sa.BIGINT(), nullable=True),
    sa.Column('characteristic_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['characteristic_id'], ['class_characteristic_op.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class_op.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_configuration_priority_criteria',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('priority_criteria_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['priority_criteria_id'], ['priority_criteria.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_schedule_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_op.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_schedule_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('day', sa.BIGINT(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('area_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course_op.id'], ),
    sa.ForeignKeyConstraint(['day'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_teacher',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_teacher_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('course_id', sa.BIGINT(), nullable=True),
    sa.Column('teacher_id', sa.BIGINT(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_op.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_op.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('restriction')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('schedule_id', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=False))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('class_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'teacher_op', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['day'], ['id'])
        batch_op.create_foreign_key(None, 'class_op', ['class_id'], ['id'])
        batch_op.create_foreign_key(None, 'course_op', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['id'])

    with op.batch_alter_table('characteristic_class', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('characteristic_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'class', ['class_id'], ['id'])
        batch_op.create_foreign_key(None, 'class_characteristic', ['characteristic_id'], ['id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'type', ['day'], ['id'])
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    with op.batch_alter_table('teacher_schedule', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'type', ['day'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('day',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('course_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('area_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('day',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semester')
        batch_op.drop_column('area_id')

    with op.batch_alter_table('characteristic_class', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('characteristic_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('class_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('class_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('schedule_id')
        batch_op.drop_column('day')

    op.create_table('restriction',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value_type', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='restriction_pkey')
    )
    op.drop_table('course_teacher_op')
    op.drop_table('course_teacher')
    op.drop_table('course_schedule_op')
    op.drop_table('teacher_schedule_op')
    op.drop_table('schedule_configuration_priority_criteria')
    op.drop_table('course_op')
    op.drop_table('characteristic_class_op')
    op.drop_table('teacher_op')
    op.drop_table('schedule')
    op.drop_table('priority_criteria')
    op.drop_table('class_op')
    op.drop_table('class_characteristic_op')
    op.drop_table('area')
    # ### end Alembic commands ###
