"""empty message

Revision ID: 7177fb88e4af
Revises: 0795c9802960
Create Date: 2023-09-04 23:37:12.935537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7177fb88e4af'
down_revision = '0795c9802960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_op',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_restriction',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('schedule_id', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_students', sa.Integer(), nullable=False))

    with op.batch_alter_table('class_op', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_capacity', sa.Integer(), nullable=False))
        batch_op.drop_column('number')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('no_periods',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('course_op', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_students', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule_id', sa.BIGINT(), nullable=True))
        batch_op.alter_column('no_periods',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['id'])

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('schedule_version_fkey', type_='foreignkey')

    with op.batch_alter_table('schedule_area_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))

    with op.batch_alter_table('schedule_class_configuration', schema=None) as batch_op:
        batch_op.drop_constraint('schedule_class_configuration_class_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_op', ['class_id'], ['id'])

    with op.batch_alter_table('teacher_op', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['id'])

    with op.batch_alter_table('teacher_schedule', schema=None) as batch_op:
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    with op.batch_alter_table('teacher_schedule_op', schema=None) as batch_op:
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'area_op', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_schedule_op', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('area_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('area_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('teacher_op', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_id')

    with op.batch_alter_table('schedule_class_configuration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('schedule_class_configuration_class_id_fkey', 'class', ['class_id'], ['id'])

    with op.batch_alter_table('schedule_area_configuration', schema=None) as batch_op:
        batch_op.drop_column('priority')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_foreign_key('schedule_version_fkey', 'type', ['version'], ['id'])
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('course_op', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('no_periods',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('schedule_id')
        batch_op.drop_column('no_students')
        batch_op.drop_column('credits')
        batch_op.drop_column('code')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('no_periods',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('class_op', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('space_capacity')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('no_students')

    op.drop_table('schedule_restriction')
    op.drop_table('area_op')
    # ### end Alembic commands ###
