"""empty message

Revision ID: 930759c4d73d
Revises: 
Create Date: 2023-08-20 17:29:55.392604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930759c4d73d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    # ### end Alembic commands ###
