"""empty message

Revision ID: 9dcdaa225622
Revises: 20ec77b2e14f
Create Date: 2023-09-18 01:45:59.372011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcdaa225622'
down_revision = '20ec77b2e14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_assignment_oc',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('no_students', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_schedule_oc', schema=None) as batch_op:
        batch_op.drop_constraint('course_schedule_oc_area_id_fkey', type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_schedule_oc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('course_schedule_oc_area_id_fkey', 'area_oc', ['area_id'], ['id'])

    op.drop_table('course_assignment_oc')
    # ### end Alembic commands ###
