"""empty message

Revision ID: dfe0ff19e16c
Revises: 13b012962059
Create Date: 2023-09-18 01:59:10.461651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe0ff19e16c'
down_revision = '13b012962059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assignment_oc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.BIGINT(), nullable=True))
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_assignment_oc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
